### ISSUE TITLE
error while executing

### ISSUE THREAD

**Issue by philipmoh** [yevgeniy-logachev/QtAdMob#15]
Hi,

I have this error while trying to compile the project.
main.obj:-1: error: LNK2019: unresolved external symbol "public: static void __cdecl QmlAdMobBanner::DeclareQML(void)" (?DeclareQML@QmlAdMobBanner@@SAXXZ) referenced in function main

What did I miss?

Thanks

**Comment by andresilvasantos** [comment]
Is QtAdMobBanner.h included in your project?

**Comment by philipmoh** [comment]
Yes...

**Comment by philipmoh** [comment]
I think I got it.
The build folder is pointing wrongly...:(
Thanks

**Comment by philipmoh** [comment]
Hi again,

Now everything runs.....but the banner is not showing....please help...
