### ISSUE TITLE
Interstitial not showing without AdMobBanner (QML)

### ISSUE THREAD

**Issue by synio-wesley** [yevgeniy-logachev/QtAdMob#18]
Hi there

I've been having a lot of troubles getting QtAdMob to work but after a while I got it to work.

It now seems like I need to have an empty AdMobBanner {} in my QML file because otherwise (for some reason) the AdMobInterstitial never shows. Is this intended behaviour? Do you have an idea where things could go wrong?

Kind regards
Wesley

**Comment by vdaele** [comment]
I think the problem is in the onAdLoaded of the interstitial AdListener. It checks on `if (m_AdBannerView == null)` which is not needed afaics.   Only
```
                            m_IsAdInterstitialLoaded = true;
                            onInterstitialLoaded();
```

seems to be sufficient.

**Comment by synio-wesley** [comment]
I'm closing this because it's about 4 years old and I'm not working with this anymore.
