### ISSUE TITLE
Use #pragma once

### ISSUE THREAD

**Issue by skynowa** [yevgeniy-logachev/QtAdMob#5]

**Comment by ildar-gilmanov** [comment]
I think, Include guard 
`#ifdef MY_HEADER_H`
`#define MY_HEADER_H`

`#endif // MY_HEADER_H`

is more portable and stable then `#pragma once`, and `#pragma once` is not in standard.

**Comment by nextgeniuspro** [comment]
I agree with gilmanov-ildar that include guard is better solution
