### ISSUE TITLE
Add simple example how to use this library

### ISSUE THREAD

**Issue by skynowa** [yevgeniy-logachev/QtAdMob#7]
https://habrahabr.ru/post/261425/

**Comment by nextgeniuspro** [comment]
Hello skynowa,

Look in README on "How to integrate" section, there is link to example project, or just click this [link](https://github.com/yevgeniy-logachev/QtAdMobApp).

Also REAMDE contain step-by-step integration for iOS and Android

And of course, that article also describes in Russian how to integrate it

**Comment by ghost** [comment]
Добрый вечер! Решил не создавать новый "issue", поэтому и пишу здесь... Никак не могу скомпилировать проект с Вашей библиотекой, а также и QtAdMobTestApp: в обоих случаях получаю одну и ту же ошибку (Указана ниже). Все делал по инструкции из репозитория (Использую Ant), все пути перепроверил, но все без толку :( С чем это может быть связано? Спасибо за ответ!

> xcopy /s /q /y /i B:/Matrix_calculator/Matrix_calculator++_(Lite)/QtAdMob/platform/android/src B:/Matrix_calculator/Matrix_calculator++_(Lite)/android;
> makefile:400: recipe for target 'copydata' failed
> ЌҐ¤®ЇгбвЁ¬®Ґ зЁб«® Ї а ¬Ґва®ў
> mingw32-make: **\* [copydata] Error 4 >

**Comment by nextgeniuspro** [comment]
Здравствуйте, хотел проверил корректность интеграции библиотеки в ваш проект, но в вашем репозитории пусто:). Поэтому проверьте что в файле проекта .pro инициализирована переменная ANDROID_PACKAGE_SOURCE_DIR = $$PWD/<путь к AndroidManifest.xml> до включения include(QtAdMob/QtAdMob.pri). Также может быть проблема из-за "++" в имени каталога, попробуйте сменить на Matrix_calculatorPlusPlus

**Comment by ildar-gilmanov** [comment]
@trstalker , было бы неплохо настроить кодировку в консоли, чтобы не было кракозябр, может там есть подсказка, которая поможет разобраться в проблеме.

**Comment by ghost** [comment]
@yevgeniy-logachev И снова добрый вечер! Еще раз все перепроверил, убрал из пути к проекту "лишние символы", но результат остался тот же - ошибка в том же месте с тем же текстом. Залил полный проект в репозиторий, может это как-то поможет в решении проблемы :)
@gilmanov-ildar буквально на той неделе обновлял весь Qt, поэтому кракозябры вернулись :)

**Comment by nextgeniuspro** [comment]
Я создал pell-request в вашем репозитории, с фиксами интеграции QtAdMob

**Comment by ghost** [comment]
@yevgeniy-logachev Проделал все изменения на чистовом проекте - результат тот же, ошибка на том же пункте. Также сделал merge вашего коммита и клонировал репозиторий - аналогично. Может это связано с самим Qt или же с сопутствующими ему Android SDK и т.п.? У Вас скомпилировался клонированный репозиторий?
