### ISSUE TITLE
Add a way to control or get the height of the statusbar on Android

### ISSUE THREAD

**Issue by larpon** [yevgeniy-logachev/QtAdMob#8]
Hi - thanks for making this project available

I'm having trouble compensating for the `m_StatusBarHeight` that is added to the AdBanner view.

I have a QML app that set the activity to fullscreen - but due to some Qt Android specific code the statusbar isn't hidden before Qt is finished loading all it's parts on Android. Somewhere in this process the `m_StatusBarHeight` is sat before the app goes into fullscreen or maybe subject to the issues some other  Stackoverflow users also have with the ["old" method](http://stackoverflow.com/a/3410200/1904615). So the ad banner has a top padding although the statusbar is hidden.

It would be nice with a fix or a method to "counter-act" the default padding - may a public method implementing [this answers current method](http://stackoverflow.com/a/3410200/1904615) or similar

**EDIT:**
2785561ae1f5cd2f1872affb0e44afa767789775 seems to do the trick

**Comment by nextgeniuspro** [comment]
Hi,
I've added your changes to repository. Thanks!

**Comment by larpon** [comment]
Awesome!
